language: ruby
rvm: 2.1
install: bundle install
branches:
  only:
    - master
env:
  global:
    secure: "L0JQ6KSGzSd5Ei84oAIQhtt2pXJMi6UMBWogoMo45r785rS0x53mPDqxMp79rCJrqfYx3wngmYrA3LqMorjpRMbgTk9CecogwFT07n5eZminau6uUO4YADiuWyC4665+6859XSTwewci+8b0MsyHkSE0RzR+EqXYtohuhsav+I0="
script: bundle exec rake site:build
after_success: bundle exec rake site:stage
