language: ruby
rvm: 2.1
install: bundle install
branches:
  only:
    - master
env:
  global:
    secure: "bYJQX5rtDnLQtr58ONs2GpXvjM8+r/SMJbDKjeZzaJLalMOJA2OkoHaqZl3XtWjMAqYfiL8Ot0QZ+JWw4ojU9GMCRaSn0wIkJx2Za+aQ57uQU1jnSM8Q6AKu6UeETf/mq6LCJnKWP9zV9v89I0oLbd6SYi8B/0dh4c+mjsHE+BI="
script: bundle exec rake site:build
after_success: bundle exec rake site:stage
