# Site settings
title: The Jonx
email: your-email@domain.com
description: >
  A place for hackers in Central Illinois.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: hackthejonx
github_username:  thejonx

# Build settings
markdown: kramdown
