# Site settings
title: The Jonx
email: https://www.google.com/recaptcha/mailhide/d?k=01nob_RSMoYcriRm7XPsVKEw==&c=jLY6WpsMFSgCG25rkcaA7w==
description: >
  A place for hackers in Central Illinois.
baseurl: ""
url: "https://thejonx.github.io"
twitter_username: hackthejonx
github_username:  thejonx

# Build settings
markdown: kramdown
