# Site settings
title: The Jonx
email: your-email@domain.com
description: >
  A place for hackers in Central Illinois.
baseurl: ""
url: "https://thejonx.github.io"
twitter_username: hackthejonx
github_username:  thejonx

# Build settings
markdown: kramdown
